### ISSUE TITLE
CP-3015 Difference to the statemachine package

### ISSUE THREAD

**Issue by enyo** [Workiva/state_machine#32]
Hey, I just wondered why you chose to create a new package when there already is the [`statemachine`](https://pub.dartlang.org/packages/statemachine) package.

I want to start adding a state machine to my code and am wondering which one to use. Thanks

**Comment by rmconsole-wf** [comment]
It looks like you have not included any tickets in the title of this issue. Please create a ticket for this issue, or click <a href='https://w-rmconsole.appspot.com/api/v1/issues/Workiva/state_machine/32/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by evanweible-wf** [comment]
@enyo For our purposes, we were looking for a state machine implementation in which we could define the state transitions, not just the states, so that we could guard against or detect illegal state transitions. However, as @mahonnaise pointed out in #24, the concept of an illegal state transition shouldn't really exist.

We would like to revisit this implementation to rectify that, but haven't had time to prioritize it. When we find the time, it's possible that this implementation and the `statemachine` package may no longer be as different - although I still think the notion of being able to define state transitions in a typed manner is useful.

**Comment by enyo** [comment]
Thanks for your answer!
